/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'dropoff' : IDL.Text,
  'carModel' : IDL.Text,
  'duration' : IDL.Nat,
  'driverRating' : IDL.Nat,
  'vehicleNumber' : IDL.Text,
  'fare' : IDL.Nat,
  'distance' : IDL.Nat,
  'pickup' : IDL.Text,
  'driverEta' : IDL.Nat,
  'userRating' : IDL.Nat,
  'rideType' : IDL.Text,
  'driverName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'read' : IDL.Bool,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotification' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'getAISuggestion' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'reasoning' : IDL.Text, 'rideType' : IDL.Text })],
      ['query'],
    ),
  'getAITripSummary' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getCallerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitDriverRating' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'dropoff' : IDL.Text,
    'carModel' : IDL.Text,
    'duration' : IDL.Nat,
    'driverRating' : IDL.Nat,
    'vehicleNumber' : IDL.Text,
    'fare' : IDL.Nat,
    'distance' : IDL.Nat,
    'pickup' : IDL.Text,
    'driverEta' : IDL.Nat,
    'userRating' : IDL.Nat,
    'rideType' : IDL.Text,
    'driverName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const Notification = IDL.Record({ 'read' : IDL.Bool, 'message' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotification' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'getAISuggestion' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'reasoning' : IDL.Text, 'rideType' : IDL.Text })],
        ['query'],
      ),
    'getAITripSummary' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getCallerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitDriverRating' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };